services:
  app:
    container_name: coworker-app
    image: coworker-backend:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - db
      - redis
    networks:
      - coworker-network

  db:
    container_name: coworker-mysql
    image: mysql:coworker
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coworker-network

  redis:
    container_name: coworker-redis
    image: redis:coworker
    restart: always
    ports:
      - "6380:6379"
    networks:
      - coworker-network


networks:
  coworker-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
