name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치 푸시 시 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Docker 이미지 빌드 & Push (멀티 아키텍처 지원)
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/coworker-backend:latest \
            --push .

      # 5. EC2 접속 후 배포 수행
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/coworker
            sudo docker-compose down
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/coworker-backend:latest
            sudo docker-compose up -d
            sudo docker image prune -f
            sudo nginx -t && sudo systemctl restart nginx
