name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 자동 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Gradle wrapper 실행 권한 부여
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # 5. JAR 파일 빌드 (테스트는 제외)
      - name: Build JAR file
        run: ./gradlew build -x test

      # 6. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Docker 이미지 빌드 & Docker Hub에 푸시
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/coworker-backend:latest \
            --push .

      # 8. EC2 접속해서 컨테이너 재시작 + Nginx 재시작
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/coworker
            sudo docker-compose down
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/coworker-backend:latest
            sudo docker-compose up -d
            sudo docker image prune -f
            sudo nginx -t && sudo systemctl restart nginx
